### ISSUE TITLE
Validation multi-feature license failed!

### ISSUE THREAD

**Issue by beizi8** [open-license-manager/licensecc#106]
1、Use lccgen license issue --primary-key data_path/private_key.rsa --output-file-name license_dir\license.lic -f PROJECT,FEATURE1
generate a license file
2、Validate the license file and only PROJECT that default project return LICENSE OK,but the FEATURE1 return "license signature didn't match with current license",something wrong ? here is code

   string fname = "...license.lic";
    LicenseInfo licenseInfo;
    LicenseLocation licLocation = { LICENSE_PATH };
    std::copy(fname.begin(), fname.end(), licLocation.licenseData);
    CC_EVENT_TYPE result = acquire_license(nullptr, &licLocation, &licenseInfo);
    if (result == LICENSE_OK) {
        cout << "default project [" << LCC_PROJECT_NAME << "]: license OK" << endl;
    } else {
        cerr << "default project [" << LCC_PROJECT_NAME << "]:" << stringByEventType[result].c_str() << endl;
    }
   //aboved code get LICENSE_OK 

     CallerInformations callerInformation;
    string section_name = "FEATURE1";
    std::copy(section_name.begin(), section_name.end(), callerInformation.feature_name);
    LCC_EVENT_TYPE result1 = acquire_license(&callerInformation, &licLocation, &licenseInfo);
    if (result1 == LICENSE_OK) {
        cout << "project [" << section_name.c_str() << "]: license OK" << endl;
    } else {
        cerr << "default project [" << section_name.c_str() << "]:" << stringByEventType[result1].c_str() << endl;
    }

//aboved code get license signature didn't match with current license

 I don't know what's wrong with me!

**Comment by gcontini** [comment]
Try to initialize `CallerInformation` to 0... Also are you sure you're terminating ('\0') the `feature_name` you're copying?

Documentation will be added soon
