### ISSUE TITLE
Can i use it for debian ?

### ISSUE THREAD

**Issue by getmlcode** [open-license-manager/licensecc#129]
I need to use the source code in order to modify it to suit my use-case, but I am working with debian.
So  I wanted to know if source code is compatible with debian ? 
I am asking this because Readme only mentions linux and windows.

**Comment by gcontini** [comment]
It "should" be compatible with Debian 9. For my personal "taste" it is compatible with the latest Ubuntu LTS that's a debian derivative... It is also tested on centos 7-8... if you have issues please reopen.
