### ISSUE TITLE
windows build lccgen fail - OpenSSL 1.0.2u

### ISSUE THREAD

**Issue by F474M0R64N4** [open-license-manager/licensecc#80]
![2020-05-23 11_12_52-licensecc - Microsoft Visual Studio  (Administrator)](https://user-images.githubusercontent.com/8020186/80075643-15f3b500-855c-11ea-8592-6fde89a98593.png)

solve problem with add `legacy_stdio_definitions.lib` to linker

fix please

**Comment by lurumdare** [comment]
and 

```
#define stdin  (__acrt_iob_func(0))
#define stdout (__acrt_iob_func(1))
#define stderr (__acrt_iob_func(2))

FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }

```

to `main.cpp`

**Comment by lurumdare** [comment]
windows 10 1909 x64

**Comment by lurumdare** [comment]
Problem on OpenSSL `1.0.2u` version. 
Add support to older versions?

**Comment by gcontini** [comment]
Thanks for reporting. I'm completing a feature, as soon as i finish the current work i'll take a look at it.
