### ISSUE TITLE
check license against a safe time source (system clock can be altered)

### ISSUE THREAD

**Issue by F474M0R64N4** [open-license-manager/licensecc#81]
the problem is that if the license has expired, then you can change the system time ago and get a valid license

should be fixed?

![2020-04-23 13_49_54-Debug](https://user-images.githubusercontent.com/8020186/80085567-70474280-8569-11ea-8211-cd73c04af6fc.png)

**Comment by gcontini** [comment]
It's a nice feature. Any advice on how to implement it?

**Comment by lurumdare** [comment]
```
const int days_after_license_start = (today - m_issue_date_).days();
		const int days_before_license_end = (m_expire_date_ - today).days();

		if (days_after_license_start < 0)
		{
			return false;
		}

		if (days_before_license_end < 0)
		{
			return false;
		}
```

My code in another project.

**Comment by senthilsam** [comment]
For every license check we can save the timestamp as "lastactive" and add one more validation during license validation as whether current timestamp is less than "lastactive" for time tweak detection.
But we need to decide where we are going to store this. may be we can choose registry. If we store on the license file then we need regenerate license everytime.

My two cents

**Comment by a1987zz** [comment]
As an option to use some time server. With this for example: [https://unixtime.co.za/](url)

**Comment by gcontini** [comment]
Both the options have their pros and cons. 
- Saving data: wherever we save the system can always be restored to its former state (eg a vm...) or the registry key can be resetted. This library is open source, it's easy to find out what we're doing. 
 - Time servers: what if we don't have an internet connection or the user blocks access to the time server?

Even if it's a nice feature (as you all are proposing it) it isn't resistant to any attack. So if some of you can provide an implementation i'll be glad to integrate it. For now i would say it's a second order priority. Saving the last date in the license file is also ok. There is the option to ignore keys when calculating the signature (eg the signature itself need to be ignored)... but just replacing the license with a former one would be enough to nullify this protection.

The definitive solution for this is using a license server to download short-lived licenses (and a safe time reference) see issue #4 .
